<?php
$categories = Mage::getModel('lcb_attachments/category')->getCollection();
$attachments = Mage::getModel('lcb_attachments/attachment')->getCollection();
?>

<?php
foreach ($categories as $category):
    $attachments = $category->getAttachments(Mage::app()->getStore()->getId());
    if ($attachments->count() > 0):
        ?>
        <h2><?php echo $this->__($category->getName()); ?></h2>
        <?php
        foreach ($attachments as $attachment):
            ?>
            <h4>
                <a href="<?php echo $attachment->getUrl(); ?>">
            <?php echo $attachment->getTitle(); ?>
                </a>
            </h4>
        <?php endforeach;
    endif;
    ?>
<?php endforeach; ?>