<?php
$attachments = $this->getAttachments();
$product = Mage::registry('current_product');
if ($product && $product->getId()):
    $attachments = Mage::getModel('lcb_attachments/product')->getCollection()->addFieldToFilter('product_id', $product->getId());
    if ($attachments->count() > 0):
        ?>
        <?php
        foreach ($attachments as $attachment):
            $attachment = Mage::getModel('lcb_attachments/attachment')->load($attachment->getAttachmentId());
            $categories[$attachment->getCategory()][] = $attachment;
        endforeach;
        foreach ($categories as $category => $attachments):
            $category = Mage::getModel('lcb_attachments/category')->load($category);
            ?>
            <h4><?php echo $category->getName(); ?></h4>
            <ul>
                <?php foreach ($attachments as $attachment):
                    ?>
                    <li><a href="<?php echo $attachment->getUrl(); ?>"><?php echo $attachment->getTitle(); ?></a></li>    
                <?php endforeach; ?>
            </ul>
            <br/>
        <?php endforeach;
        ?>
        <?php
    endif;
endif;
?>
