<?php
$product = Mage::registry('current_product');
if ($product && $product->getId()):
    $attachments = Mage::getModel('lcb_attachments/product')->getCollection()->addFieldToFilter('product_id', $product->getId());
    if ($attachments->count() > 0):
        ?>
        <ul>
            <?php
            foreach ($attachments as $attachment):
                $attachment = Mage::getModel('lcb_attachments/attachment')->load($attachment->getId());
                $category = Mage::getModel('lcb_attachments/category')->load($attachment->getCategory());
                ?>
                <h4><?php echo $category->getName(); ?></h4>
                <li><a href="<?php echo $attachment->getUrl(); ?>"><?php echo $attachment->getTitle(); ?></a></li>    
            <?php endforeach; ?>
        </ul>
        <?php
    endif;
endif;
?>
